-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 09:49:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema introdb61479
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema introdb61479
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `introdb61479` DEFAULT CHARACTER SET utf8 ;
USE `introdb61479` ;

-- -----------------------------------------------------
-- Table `introdb61479`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introdb61479`.`marcas` (
  `idMarca` TINYINT NOT NULL AUTO_INCREMENT,
  `mkNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introdb61479`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introdb61479`.`categorias` (
  `idCategoria` TINYINT NOT NULL AUTO_INCREMENT,
  `catNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introdb61479`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introdb61479`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `prdNombre` VARCHAR(45) NOT NULL,
  `prdPrecio` FLOAT(9,2) NOT NULL,
  `idMarca` TINYINT NOT NULL,
  `idCategoria` TINYINT NOT NULL,
  `prdDescripcion` VARCHAR(100) NOT NULL,
  `prdImagen` VARCHAR(45) NOT NULL,
  `prdActivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_marca_idx` (`idMarca` ASC) VISIBLE,
  INDEX `fk_categoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_marca`
    FOREIGN KEY (`idMarca`)
    REFERENCES `introdb61479`.`marcas` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `introdb61479`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
